Added Movie List database
FifthTry/movie-db pull request #1
Opened 2022-08-17 07:57 UTC by ADITIRAI290698

Added 1 database wrt to response, movie and record.

2022-08-17 10:15 UTC, amitu commented on dj/movies/views.py
> +    return django.http.JsonResponse([record_response,record_movie,record_review], status=200)
Use `black` to format source code. https://pypi.org/project/black/

2022-08-19 08:29 UTC, AbrarNitk requested changes

2022-08-19 08:29 UTC, AbrarNitk commented on dj/movies/serializers.py
> +from rest_framework import serializers
Remove `rest_framework` we don't require this. I have already sent you a template please use that. `django.http.JsonResponse` will work.

2022-08-19 08:29 UTC, AbrarNitk commented on dj/movies/views.py
> +from .serializers import MovieSerializer
Remove serializers

2022-08-19 08:29 UTC, AbrarNitk commented on dj/movies/views.py
> +@api_view(['GET','POST'])
Remove this `api_view`

2022-09-01 18:38 UTC, AviralVerma13 commented
This PR is redundant and not is use now. refer https://github.com/FifthTry/movie-db/pull/7 now

2022-09-01 18:38 UTC, closed without merging