Change URL: add_movie: `_` to `-` and add_review: `_` to `-`
FifthTry/movie-db pull request #14
Opened 2022-09-09 06:47 UTC by ADITIRAI290698

2022-09-09 07:11 UTC, ADITIRAI290698 commented
@AbrarNitk please review the PR and merge it.

2022-09-13 05:35 UTC, AbrarNitk requested changes

2022-09-13 05:35 UTC, AbrarNitk commented on dj/ui/add-movie.ftd
> +url: /add_movie/
It should be `add-movie`

2022-09-13 09:11 UTC, ADITIRAI290698 commented
@AbrarNitk  Done the required changes. Please check and please merge the PR.

2022-09-21 15:56 UTC, AbrarNitk commented
This PR is no longer required.

2022-09-21 15:56 UTC, closed without merging